# Generated by Django 5.2.5 on 2025-08-09 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registration_attended_registration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 18, 11, 27, 567995, tzinfo=datetime.timezone.utc)),
        ),
    ]
