# Generated by Django 5.2.5 on 2025-08-10 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_start_time_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(default='Untitled Certificate', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 11, 26, 5, 64334, tzinfo=datetime.timezone.utc)),
        ),
    ]
