# Generated by Django 5.2.5 on 2025-08-10 12:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_certificate_name_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 12, 3, 44, 247749, tzinfo=datetime.timezone.utc)),
        ),
    ]
