# Generated by Django 5.2.5 on 2025-08-10 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_certificate_event_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='event',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 13, 8, 54, 306425, tzinfo=datetime.timezone.utc)),
        ),
    ]
