# Generated by Django 5.2.5 on 2025-08-10 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_certificate_event_alter_certificate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 19, 29, 20, 878397, tzinfo=datetime.timezone.utc)),
        ),
    ]
