# Generated by Django 5.2.5 on 2025-08-10 20:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_certificate_event_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates_of_event', to='events.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 20, 52, 10, 566942, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_real', to='events.event'),
        ),
    ]
