# Generated by Django 5.2.5 on 2025-08-10 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_certificate_event_alter_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 21, 7, 22, 582623, tzinfo=datetime.timezone.utc)),
        ),
    ]
