# Generated by Django 5.2.5 on 2025-08-10 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 21, 8, 8, 783316, tzinfo=datetime.timezone.utc)),
        ),
    ]
