# Generated by Django 5.2.5 on 2025-08-10 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas_of_interest',
            field=models.ManyToManyField(blank=True, to='events.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 22, 2, 20, 581498, tzinfo=datetime.timezone.utc)),
        ),
    ]
