# Generated by Django 5.2.5 on 2025-08-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
