# Generated by Django 5.2.5 on 2025-08-27 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_registration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='responses',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('file', 'File'), ('email', 'Email')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='events.event')),
            ],
        ),
    ]
