# Generated by Django 5.2.5 on 2025-08-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_remove_eventregistration_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='registration_files/'),
        ),
    ]
