# Generated by Django 5.2.5 on 2025-08-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_registration_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('file', 'File'), ('email', 'Email'), ('url', 'Url')], default='text', max_length=20),
        ),
    ]
